### ISSUE TITLE
svg highlighting

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#25]
As the svg rectangles in layer elements overlay the staff lines  (e.g. see http://probstuecke-digital.de/7) it may be good to use pure css to highlight something.
We could introduce something like:
```css
g.blink {
animation: blinking 1s infinite;
}

@keyframes blinking {
  0% {fill: red;}
  50% {fill: black;}
  100% {fill: red;}
}
```
and use js to change the class of all referenced elements on click. 
The continued blinking helps to better track down the highlighted elements.
