### ISSUE TITLE
title page

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#94]
We should have a 'real' title page, stating the name of the project etc. 

Also, the regularized text I added to the front page is shown normally, but should be a tooltip or pop-over ideally … 
For now I would simply make:
```css
tei-choice tei-reg {
  display: none;
}

```
